KS-22-5 Создание класса данных для хранения информации о местах и соб…
Untamos25/KotlinSprint pull request #114
Opened 2024-09-15 10:07 UTC by Untamos25

…ытиях в голактике

2024-09-15 12:53 UTC, ievetrovdev requested changes

2024-09-15 14:21 UTC, Untamos25 commented on src/main/kotlin/lesson_22/lesson22_task5.kt
> +    println("Название: ${alphaCentauri.name}")
Не сразу понял, в чём суть компонентных функций, Сейчас разобрался поглубже и исправил решение, но всё равно до сих пор не могу понять разницы между мульти-декларацией и деструктуризацией экземпляров классов данных. За счёт того, что в классах данных уже переопределены функции componentN(), реализация выше сказанного по факту одинаковая, если требуется создать переменные для всех свойств класса. Разве что, если я правильно понял, при деструктуризации при необходимости мы можем обращаться к отдельным свойствам, а не ко всем сразу. Только в этом принципиальное отличие или есть ещё что-то, что я упускаю?

2024-09-16 07:16 UTC, ievetrovdev requested changes

2024-09-16 11:16 UTC, Untamos25 commented on src/main/kotlin/lesson_22/lesson22_task5.kt
> +data class GalacticGuide(
Спасибо за комментарий! С этой частью разобрался 👍

2024-09-16 11:17 UTC, Untamos25 commented on src/main/kotlin/lesson_22/lesson22_task5.kt
> +    val (name, description, dateTime, distanceFromEarth) = alphaCentauri
Согласен, что лучше знать)

2024-09-16 14:36 UTC, ievetrovdev approved these changes

2024-09-16 15:09 UTC, merged